스크롤 이벤트에 반응하는 네브바 구성
meet-in-ssafy/service pull request #14
Opened 2021-07-23 07:47 UTC by Dongkyun-Jang

- https://github.com/n8tb1t/use-scroll-position

해당 주소의 커스텀훅을 활용하였습니다. 이전 스크롤 위치와 현재 스크롤 위치를 비교할 때 유용하게 사용할 수 있습니다.

2021-07-23 09:08 UTC, dididy requested changes
전체적으로 공부할 부분이 많은 코드였습니다 

정상 작동 확인했어요

수고 많으셨습니다!!

2021-07-23 09:08 UTC, dididy commented on FE/hooks/useWindow.ts
> +  typeof window !== 'undefined' ? useLayoutEffect : useEffect;
window 객체가 없으면 useLayoutEffect로 처리되게끔 되거있네요

찾아보니 useLayoutEffect는 useEffect와 다르게 동기적으로 처리되고 화면이 그려지기 이전에 실행되는군요

2021-07-23 09:08 UTC, dididy commented on FE/hooks/useWindow.ts
> +const isBrowser = typeof window !== `undefined`;
추가적으로 window 객체의 타입이 undefined인 시점인 언제인지를 공부해봐야겠네요

변수명으로 미루어보아 브라우저가 아닌 경우인 것일까요?

2021-07-23 09:08 UTC, dididy commented on FE/hooks/useWindow.ts
> +  element?.getBoundingClientRect();
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

이것도 처음보네요

2021-07-23 09:08 UTC, dididy commented on FE/hooks/useWindow.ts
> +  element?: ElementRef,
NavBar 컴포넌트에서 이 라인에 의해 타입에러가 발생하는 것 같습니다 undefined도 고려되어야 할 것 같아요

2021-07-23 09:08 UTC, dididy commented on FE/hooks/useWindow.ts
> +      window.addEventListener('scroll', handleScroll, { passive: true });
https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners

passive 옵션도 처음봤네요

2021-07-24 04:44 UTC, Dongkyun-Jang commented on FE/hooks/useWindow.ts
> +const isBrowser = typeof window !== `undefined`;
SSR에서 window 객체를 얻는게 까다로운 일인 것 같더라고요. 이 부분은 저도 애를 많이 먹어서 문서화해서 공유하도록 하겠습니다.

2021-07-24 04:45 UTC, Dongkyun-Jang commented on FE/hooks/useWindow.ts
> +  element?: ElementRef,
저도 그것 때문에 null 대신 undefined를 적어봤는데, 그렇게 할 경우 타입에러는 발생하지 않더라고요. 
그런데 undefined를 명시적으로 할당해도 될 지 잘 모르겠어서 일단 이렇게 두어봤습니다!!

2021-07-24 04:51 UTC, dididy commented on FE/hooks/useWindow.ts
> +  element?: ElementRef,
넵 알겠습니다!

2021-07-24 04:52 UTC, dididy approved these changes
수고하셨습니당

2021-07-24 04:54 UTC, minho-jang approved these changes

2021-07-24 05:51 UTC, minho-jang commented on FE/hooks/useWindow.ts
> +const isBrowser = typeof window !== `undefined`;
저도 비슷한 이슈가 있었습니다 OpenVidu가 프론트에 최적화 되어있어서 그냥 import하면 라이브러리 내에서 window를 참조해서 에러가 발생하더라고요. 그래서 저는 라이브러리를 동적으로 import 했습니다.

2021-07-24 12:38 UTC, merged